const assert=require('node:assert/strict'),fs=require('node:fs');const {boot}=require('./gba-core.cjs');
(async()=>{const g=await boot();g.capture('gba-title');g.tap(8);assert.equal(g.read('game_mode'),4);g.capture('gba-map');g.tap(16);g.tap(1);assert.equal(g.read('game_mode'),4,'Locked district entered');g.tap(32);g.tap(1);assert.equal(g.read('game_mode'),5);g.capture('gba-briefing');g.tap(1);assert.equal(g.read('game_mode'),1);g.capture('gba-first-delivery');
const neighbors=[[0,1,1,2],[0,3,1,2],[0,4,1,2],[1,5,3,4],[2,5,3,4],[3,5,3,4]],nav=[32,16,64,128];
for(let room=0;room<18;room++){
 if(room&&room%3===0){const target=Math.floor(room/3),queue=[[g.read('selected'),[]]],seen=new Set();while(queue.length){const [n,route]=queue.shift();if(n===target){route.forEach(k=>g.tap(k));break;}if(seen.has(n))continue;seen.add(n);neighbors[n].forEach((v,i)=>queue.push([v,[...route,nav[i]]]));}g.tap(1);g.tap(1);}
 assert.equal(g.read('game_mode'),1);assert.equal(g.read('room_id'),room);
 const route=JSON.parse(fs.readFileSync(`artifacts/gba-route-letter-${room}.json`)),deaths=g.read('deaths'),before=g.read('simulation_frames'),start=g.read('frame_tick'),overruns=g.read('render_overruns');let moves=0,maxCamera=0,minY=144,maxY=0;
 for(const action of route){const keys=[32,16,64,128,1,2].reduce((k,v,i)=>k|((action&(1<<i))?v:0),0);for(let f=0;f<6;f++){g.run(keys);moves++;maxCamera=Math.max(maxCamera,g.read('camera'));minY=Math.min(minY,g.read('camera_y'));maxY=Math.max(maxY,g.read('camera_y'));assert.ok(g.read('camera')<=1232&&g.read('camera_y')<=144,'Camera stays within the route');if(moves===150)g.capture('gba-room-'+room);if(g.read('game_mode')!==1||g.read('deaths')!==deaths)break;}if(g.read('game_mode')!==1||g.read('deaths')!==deaths)break;}
 const result={room:room+1,moves,mode:g.read('game_mode'),deaths:g.read('deaths')-deaths,relays:g.read(g.symbols.player+23,1),letter:g.read(g.symbols.player+24,1),camera:maxCamera,simulation:g.read('simulation_frames')-before,video:g.read('frame_tick')-start};console.log(`[${room+1}/18] GBA cartridge`,result);
 assert.equal(g.read('render_overruns'),overruns,'Gameplay work must fit within one native frame');assert.equal(result.deaths,0);assert.equal(result.mode,6);assert.equal(result.relays,3);assert.equal(result.letter,1);assert.ok(maxCamera+240>=1440,'Delivery beacon is visible at the end of the route');assert.ok(maxY-minY>16,'Camera follows the vertical route');assert.ok(result.video<=result.simulation+2,'Must sustain one physics update per frame');
 g.capture('gba-delivery-'+room);g.tap(1);if(room%3===2){assert.equal(g.read('game_mode'),7);g.run(0,40);g.capture('gba-restoration-'+Math.floor(room/3));g.tap(1);if(room===17){assert.equal(g.read('game_mode'),10);g.run(0,20);g.capture('gba-homecoming');g.tap(1);}}
}
const save=g.sram();assert.equal(save[0],0x41);assert.equal(save[1],2);assert.deepEqual(Array.from(save.slice(3,9)),[3,3,3,3,3,3]);assert.deepEqual(Array.from(save.slice(22,25)),[255,255,3]);g.run(0,3);g.capture('gba-restored-map');g.tap(1);g.tap(16);g.tap(16);g.tap(4);assert.equal(g.read('game_mode'),9);g.run(0,3);g.capture('gba-last-letter');
fs.writeFileSync("artifacts/gba-complete.sav",save);const reload=await boot(save);for(let i=0;i<6;i++)assert.equal(reload.read(reload.symbols.city+i,1),3);console.log('PASS: all 18 GBA rooms, letters, branching map, residents, restorations, ending, room replay and native SRAM reload.');
const old=new Uint8Array(save);old[0]=0x50;old[1]=3;const isolated=await boot(old);assert.equal(isolated.read(isolated.symbols.city,1),0);console.log('PASS: Color saves are not accepted by the Advance cartridge.');
})().catch(e=>{console.error(e);process.exit(1)});
