"""Advance dialogue: complete thoughts, clear jobs, 30-column hardware text."""
from pathlib import Path

people=['MARA / DISPATCH','BO / FOREMAN','IVY / GARDENER','KIT / LIFT KEEPER','SOL / SKY WATCHER','NELL / ENGINEER']
missions=[
 ('THE STORM BROKE OUR CITY.','FIX BOTH POSTS. REACH MARA.'),
 ('BO NEEDS HIS FACTORY BACK.','FIX THE POSTS. WATCH FOR BOTS.'),
 ('IVY NEEDS WATER FOR PLANTS.','CLIMB ROPES. FIX THE PUMPS.'),
 ('KIT MUST SEND FOOD UPSTAIRS.','SPRINGS HELP YOU REACH DOCKS.'),
 ('SOL MUST GUIDE OUR COURIERS.','RIDE WIND. LIGHT THE BEACON.'),
 ('NELL CAN RESTART THE CITY.','CROSS COILS WHEN THEY ARE DIM.')]
radio=[
 ('MARA: THE RADIO WORKS AGAIN!','MARA: LIGHTS ON! COME FIND ME.'),
 ('MARA: BO CAN HEAR US NOW.','MARA: HIS ROAD IS LIT AGAIN.'),
 ('MARA: TWO NEIGHBORS NEED HELP.','MARA: BO AND IVY ARE WAITING.'),
 ('BO: THE STORM BROKE OUR BOTS.','BO: OUR WORKSHOP HAS POWER!'),
 ('BO: I CAN CALL THE LIFT NOW.','BO: WE CAN SEND FOOD TO KIT.'),
 ('BO: THE FACTORY IS CONNECTED.','BO: KIT CAN START THE LIFTS.'),
 ('IVY: THE PUMP HEARS US NOW.','IVY: THE WATER IS BACK!'),
 ('IVY: THE NEXT PUMP IS READY.','IVY: WATER REACHED THE TREES.'),
 ('IVY: SOL CAN HEAR ME NOW.','IVY: TAKE MY SEEDS UP TO SOL.'),
 ('KIT: BO SAYS YOU CAN HELP.','KIT: THE FIRST LIFT IS MOVING!'),
 ('KIT: THE UPPER DOCK IS READY.','KIT: FOOD IS ON ITS WAY UP.'),
 ('KIT: NELL, CAN YOU HEAR US?','KIT: POWER IS REACHING NELL.'),
 ('SOL: IVY SAID YOU WOULD COME.','SOL: THE WIND VANE IS WORKING.'),
 ('SOL: I CAN CALL THE COURIERS.','SOL: THEY CAN SEE THE BEACON.'),
 ('SOL: NELL KNOWS THE WAY HOME.','SOL: THE ROAD TO NELL IS OPEN.'),
 ('NELL: ONE CONNECTION IS BACK.','NELL: THE ENGINE HAS POWER.'),
 ('NELL: EVERYONE IS CONNECTED.','NELL: ONE MORE ROUTE TO FIX.'),
 ('MARA: WE CAN ALL HEAR YOU!','MARA: LIGHTS ON! COME HOME.')]
deliveries=[
 ('YOU FIXED MY RADIO AND LIGHTS!','EVERY ROUTE HAS TWO POSTS.','FIX BOTH, THEN COME FIND ME.'),
 ('BO RUNS THE FACTORY.','HE HAS FOOD BUT NO LIFT.','LET US RECONNECT HIS ROAD.'),
 ('OUR STREETS ARE CONNECTED!','CHOOSE BO OR IVY ON THE MAP.','BOTH NEED OUR HELP.'),
 ('THE STORM SCRAMBLED OUR BOTS.','STOMP OR DASH THROUGH THEM.','THANKS FOR FIXING MY WORKSHOP.'),
 ('THOSE BOXES HOLD FOOD.','PEOPLE LIVE ABOVE THE CLOUDS.','THEY NEED THEIR LIFTS BACK.'),
 ('THE FACTORY IS WORKING AGAIN!','KIT RUNS THE LIFTS ABOVE US.','HE CAN SEND OUR FOOD UP NOW.'),
 ('MY PLANTS WERE DRYING OUT.','YOU BROUGHT THE WATER BACK!','THE NEXT PUMP HELPS THE TREES.'),
 ('THE TREES HAVE WATER AGAIN.','I SAVED SEEDS FOR THE ROOFS.','SOL CAN HELP US PLANT THEM.'),
 ('THE GARDENS ARE GROWING AGAIN!','SOL LIVES AT THE OBSERVATORY.','TAKE THESE SEEDS UP TO HIM.'),
 ('BO SENT THE FOOD HE PROMISED.','YOU GOT OUR FIRST LIFT MOVING!','LET US REACH THE UPPER DOCK.'),
 ('FAMILIES ARE WAITING UP THERE.','NOW WE CAN SEND THEM SUPPLIES.','ONE MORE LIFT NEEDS POWER.'),
 ('ALL OUR LIFTS ARE WORKING!','NELL NEEDS POWER FOR THE CITY.','OUR CABLE CAN REACH HER NOW.'),
 ('THANK YOU FOR IVY\'S SEEDS.','I WILL PLANT THEM UP HERE.','FIRST, LET US FIX THE BEACON.'),
 ('OUR COURIERS WERE LOST IN FOG.','THIS LIGHT WILL GUIDE THEM.','THE LAST BEACON POINTS HOME.'),
 ('EVERY COURIER CAN FIND HOME!','MEET NELL AT STORM HEART.','SHE ALSO NEEDS KIT\'S POWER.'),
 ('I COULD NOT START THIS ALONE.','YOU RECONNECTED THE ENGINE.','JUST TWO MORE ROUTES TO FIX.'),
 ('BO, IVY, KIT AND SOL HELPED.','YOU CONNECTED THEIR WORK.','NOW REPAIR THE LAST ROUTE.'),
 ('THE CITY HAS ITS LIGHTS BACK.','YOU HELPED US HELP EACH OTHER.','WELCOME HOME, COURIER!')]
letters=[
 ('TO OUR COURIER,','IF THE LIGHTS GO OUT,','WE WILL WAIT FOR YOU.'),
 ('MARA, KEEP YOUR RADIO CLOSE.','HEARING YOUR VOICE HELPS','WHEN THE STREETS ARE DARK.'),
 ('A NOTE FOR THE NEW COURIER:','CYAN POSTS FIX THE RADIOS.','AMBER POSTS BRING BACK POWER.'),
 ('BO, PLEASE SAVE MY PLACE.','I WILL COME BACK TO WORK','WHEN THE ROADS ARE SAFE.'),
 ('KIT, THE SMALL BOX HAS SEEDS.','PLEASE KEEP THEM DRY.','LOVE, IVY'),
 ('TO THE NIGHT CREW,','COME HOME WHEN YOU CAN.','WE KEPT YOUR SUPPER WARM.'),
 ('IVY, I PLANTED A SEED TODAY','JUST LIKE YOU SHOWED ME.','I WILL WATER IT EVERY DAY.'),
 ('DEAR GRANDAD,','OUR LITTLE TREE GREW!','COME AND SEE IT SOON!'),
 ('SOL, PLEASE TAKE THESE SEEDS','TO THE EMPTY ROOFTOPS.','LET US MAKE THEM GREEN. - IVY'),
 ('KIT, I WAS SCARED OF LIFTS.','NOW I WANT TO RIDE UP AGAIN!','CAN I PRESS THE BUTTON?'),
 ('TO THE FAMILY AT THE TOP,','THERE IS ROOM ON OUR LIFT.','WE ARE COMING FOR YOU.'),
 ('DEAR COURIER, I SAW YOU JUMP.','MY GRANDAD AND I CHEERED!','I WANT TO TRY THAT TOO.'),
 ('SOL, IS THE STORM OVER YET?','I MISS LOOKING AT THE STARS.','TELL US WHEN THEY RETURN.'),
 ('IVY, YOUR SEEDS TOOK ROOT!','A LITTLE GREEN LEAF CAME OUT.','I WANTED YOU TO KNOW.'),
 ('TO EVERYONE DOWN BELOW,','I CAN SEE YOUR LIGHTS AGAIN.','YOU ARE NOT ALONE. - SOL'),
 ('NELL, WE SAVED SOME SUPPLIES.','THE COURIER IS BRINGING THEM.','WE WILL HELP YOU START AGAIN.'),
 ('TO OUR COURIER,','WE WERE CHEERING ON THE RADIO','EVERY STEP OF THE WAY.'),
 ('TO YOU,','WE LEFT THE LIGHT ON.','WELCOME HOME.')]
restoration=[
 ('SPARK DISTRICT IS LIT AGAIN.','BO NEEDS HELP AT THE FACTORY.','IVY NEEDS WATER FOR PLANTS.'),
 ('THE FACTORY CAN SEND SUPPLIES.','HELP KIT REPAIR THE LIFTS','TO TAKE FOOD TO FAMILIES.'),
 ('THE GARDENS HAVE WATER AGAIN.','HELP SOL AT THE OBSERVATORY','SO HE CAN LIGHT THE WAY HOME.'),
 ('THE LIFTS MOVE FOOD AND POWER.','NELL CAN USE THIS POWER FOR','THE ENGINE AT STORM HEART.'),
 ('COURIERS CAN FIND HOME.','ONCE KIT\'S LIFTS ARE REPAIRED,','YOU CAN REACH NELL TOGETHER.'),
 ('ALL SIX NEIGHBORHOODS ARE LIT.','YOU BROUGHT THE CITY TOGETHER.','NOW EVERYONE CAN FIND HOME.')]

import json
code='#include "story.h"\n'
code+='const char *const people[6]={'+','.join(json.dumps(p) for p in people)+'};\n'
for name,data in [('missions',missions),('radio_lines',radio),('deliveries',deliveries),('letters',letters),('restoration',restoration)]:
 for rows in data:
  for line in rows:assert len(line)<=30,(name,len(line),line)
 code+=f'const char *const {name}[{len(data)}][{len(data[0])}]={{'+','.join('{'+','.join(json.dumps(line) for line in row)+'}' for row in data)+'};\n'
Path('src/gba/generated/story.c').write_text(code)
